init:
  - dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

configuration: Release

before_build:
- cd src
- nuget restore

image: Visual Studio 2019

build:
  verbosity: minimal

test_script:
  - cd
  - cd ..\devops\test
  - test-all.bat
  - cd ..\..\

artifacts:
  
  - name: Living Documentation
    path: .\src\LogoFX.Bootstrapping.Specs\bin\Release\LivingDoc.html 
