init:
  - dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

configuration: Release

before_build:
- cd src
- nuget restore

image: Visual Studio 2019

build:
  verbosity: minimal
  project: ./src/LogoFX.Bootstrapping.sln

test_script:  
  - cd ../devops/test
  - test-all.bat
  - cd ../..

after_test:  
  - cd ./devops
  - cd pack
  - pack

artifacts:

  - name: Packages
    path: ./output/*.nupkg
  
  - name: Living Documentation
    path: ./src/LogoFX.Bootstrapping.Specs/bin/Release/LivingDoc.html 
